# Generated by Django 4.2.6 on 2023-10-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTICEBOARD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='photo',
            field=models.ImageField(null=True, upload_to='.Photos'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
