# Generated by Django 4.2.6 on 2023-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTICEBOARD', '0002_notice_photo_alter_notice_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(null=True, upload_to='Photos/'),
        ),
    ]
