# Generated by Django 4.2.6 on 2023-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTICEBOARD', '0005_alter_notice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/'),
        ),
    ]
